/*
 * asn1type.c
 */

/*
 * Copyright (C) 2007, Simon Kilvington
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "asn1type.h"

#define MATCH(NAME, TYPE)	if(strcmp(name, #NAME) == 0) return ASN1TYPE_ ## TYPE;

enum asn1type
asn1type(const char *name)
{
	MATCH(InterchangedObject, CHOICE)
	MATCH(Group, SET)	// MATCH(GroupClass, SET)
	MATCH(StandardIdentifier, SEQUENCE)
	MATCH(GroupItem, CHOICE)
	MATCH(ApplicationClass, SET)
	MATCH(DefaultAttribute, CHOICE)
	MATCH(FontBody, CHOICE)
	MATCH(SceneClass, SET)
	MATCH(SceneCoordinateSystem, SEQUENCE)
	MATCH(AspectRatio, SEQUENCE)
	MATCH(NextScene, SEQUENCE)
	MATCH(Ingredient, SET)	// MATCH(IngredientClass, SET)
	MATCH(ContentBody, CHOICE)
	MATCH(ReferencedContent, SEQUENCE)
	MATCH(LinkClass, SET)
	MATCH(LinkCondition, SEQUENCE)
	MATCH(EventTypeEnum, ENUMERATED)	// MATCH(EventType, ENUMERATED)
	MATCH(EventDataBody, CHOICE)	// MATCH(EventData, CHOICE)
	MATCH(Program, SET)	// MATCH(ProgramClass, SET)
	MATCH(ResidentProgramClass, SET)
	MATCH(RemoteProgramClass, SET)
	MATCH(InterchangedProgramClass, SET)
	MATCH(PaletteClass, SET)
	MATCH(FontClass, SET)
	MATCH(CursorShapeClass, SET)
	MATCH(Variable, SET)	// MATCH(VariableClass, SET)
	MATCH(OriginalValueBody, CHOICE)	// MATCH(OriginalValue, CHOICE)
	MATCH(BooleanVariableClass, SET)
	MATCH(IntegerVariableClass, SET)
	MATCH(OctetStringVariableClass, SET)
	MATCH(ObjectRefVariableClass, SET)
	MATCH(ContentRefVariableClass, SET)
	MATCH(PresentableClass, SET)
	MATCH(TokenManagerClass, SET)
	MATCH(Movement, SEQUENCE)
	MATCH(TokenGroupBody, SET)	// MATCH(TokenGroupClass, SET)
	MATCH(TokenGroupItem, SEQUENCE)
	MATCH(ActionSlot, CHOICE)
	MATCH(ListGroupClass, SET)
	MATCH(Visible, SET)	// MATCH(VisibleClass, SET)
	MATCH(BoxSize, SEQUENCE)	// MATCH(OriginalBoxSize, SEQUENCE)
	MATCH(BitmapClass, SET)
	MATCH(LineArtBody, SET)	// MATCH(LineArtClass, SET)
	MATCH(RectangleClass, SET)
	MATCH(DynamicLineArtClass, SET)
	MATCH(TextBody, SET)	// MATCH(TextClass, SET)
	MATCH(JustificationEnum, ENUMERATED)	// MATCH(Justification, ENUMERATED)
	MATCH(LineOrientationEnum, ENUMERATED)	// MATCH(LineOrientation, ENUMERATED)
	MATCH(StartCornerEnum, ENUMERATED)	// MATCH(StartCorner, ENUMERATED)
	MATCH(StreamClass, SET)
	MATCH(StreamComponent, CHOICE)
	MATCH(StorageEnum, ENUMERATED)	// MATCH(Storage, ENUMERATED)
	MATCH(AudioClass, SET)
	MATCH(VideoClass, SET)
	MATCH(TerminationEnum, ENUMERATED)	// MATCH(Termination, ENUMERATED)
	MATCH(RTGraphicsClass, SET)
	MATCH(Interactible, SET)	// MATCH(InteractibleClass, SET)
	MATCH(SliderClass, SET)
	MATCH(OrientationEnum, ENUMERATED)	// MATCH(Orientation, ENUMERATED)
	MATCH(SliderStyleEnum, ENUMERATED)	// MATCH(SliderStyle, ENUMERATED)
	MATCH(EntryFieldClass, SET)
	MATCH(InputTypeEnum, ENUMERATED)	// MATCH(InputType, ENUMERATED)
	MATCH(HyperTextClass, SET)
	MATCH(Button, SET)	// MATCH(ButtonClass, SET)
	MATCH(HotspotClass, SET)
	MATCH(PushButtonBody, SET)	// MATCH(PushButtonClass, SET)
	MATCH(SwitchButtonClass, SET)
	MATCH(ButtonStyleEnum, ENUMERATED)	// MATCH(ButtonStyle, ENUMERATED)
	MATCH(ActionClass, SEQUENCE)
	MATCH(ElementaryAction, CHOICE)
	MATCH(Add, SEQUENCE)
	MATCH(AddItem, SEQUENCE)
	MATCH(Append, SEQUENCE)
	MATCH(Call, SEQUENCE)
	MATCH(CallActionSlot, SEQUENCE)
	MATCH(Clone, SEQUENCE)
	MATCH(CloseConnection, SEQUENCE)
	MATCH(DelItem, SEQUENCE)
	MATCH(DeselectItem, SEQUENCE)
	MATCH(Divide, SEQUENCE)
	MATCH(DrawArc, SEQUENCE)
	MATCH(DrawLine, SEQUENCE)
	MATCH(DrawOval, SEQUENCE)
	MATCH(DrawPolygon, SEQUENCE)
	MATCH(DrawPolyline, SEQUENCE)
	MATCH(DrawRectangle, SEQUENCE)
	MATCH(DrawSector, SEQUENCE)
	MATCH(Fork, SEQUENCE)
	MATCH(GetAvailabilityStatus, SEQUENCE)
	MATCH(GetBoxSize, SEQUENCE)
	MATCH(GetCellItem, SEQUENCE)
	MATCH(GetCursorPosition, SEQUENCE)
	MATCH(GetEngineSupport, SEQUENCE)
	MATCH(GetEntryPoint, SEQUENCE)
	MATCH(GetFillColour, SEQUENCE)
	MATCH(GetFirstItem, SEQUENCE)
	MATCH(GetHighlightStatus, SEQUENCE)
	MATCH(GetInteractionStatus, SEQUENCE)
	MATCH(GetItemStatus, SEQUENCE)
	MATCH(GetLabel, SEQUENCE)
	MATCH(GetLastAnchorFired, SEQUENCE)
	MATCH(GetLineColour, SEQUENCE)
	MATCH(GetLineStyle, SEQUENCE)
	MATCH(GetLineWidth, SEQUENCE)
	MATCH(GetListItem, SEQUENCE)
	MATCH(GetListSize, SEQUENCE)
	MATCH(GetOverwriteMode, SEQUENCE)
	MATCH(GetPortion, SEQUENCE)
	MATCH(GetPosition, SEQUENCE)
	MATCH(GetRunningStatus, SEQUENCE)
	MATCH(GetSelectionStatus, SEQUENCE)
	MATCH(GetSliderValue, SEQUENCE)
	MATCH(GetTextContent, SEQUENCE)
	MATCH(GetTextData, SEQUENCE)
	MATCH(GetTokenPosition, SEQUENCE)
	MATCH(GetVolume, SEQUENCE)
	MATCH(Modulo, SEQUENCE)
	MATCH(Move, SEQUENCE)
	MATCH(MoveTo, SEQUENCE)
	MATCH(Multiply, SEQUENCE)
	MATCH(OpenConnection, SEQUENCE)
	MATCH(PutBefore, SEQUENCE)
	MATCH(PutBehind, SEQUENCE)
	MATCH(ReadPersistent, SEQUENCE)
	MATCH(ScaleBitmap, SEQUENCE)
	MATCH(ScaleVideo, SEQUENCE)
	MATCH(ScrollItems, SEQUENCE)
	MATCH(SelectItem, SEQUENCE)
	MATCH(SendEvent, SEQUENCE)
	MATCH(SetBoxSize, SEQUENCE)
	MATCH(SetCachePriority, SEQUENCE)
	MATCH(SetCounterEndPosition, SEQUENCE)
	MATCH(SetCounterPosition, SEQUENCE)
	MATCH(SetCounterTrigger, SEQUENCE)
	MATCH(SetCursorPosition, SEQUENCE)
	MATCH(SetCursorShape, SEQUENCE)
	MATCH(SetData, SEQUENCE)
	MATCH(SetEntryPoint, SEQUENCE)
	MATCH(SetFillColour, SEQUENCE)
	MATCH(SetFirstItem, SEQUENCE)
	MATCH(SetFontRef, SEQUENCE)
	MATCH(SetHighlightStatus, SEQUENCE)
	MATCH(SetInteractionStatus, SEQUENCE)
	MATCH(SetLabel, SEQUENCE)
	MATCH(SetLineColour, SEQUENCE)
	MATCH(SetLineStyle, SEQUENCE)
	MATCH(SetLineWidth, SEQUENCE)
	MATCH(SetOverwriteMode, SEQUENCE)
	MATCH(SetPaletteRef, SEQUENCE)
	MATCH(SetPortion, SEQUENCE)
	MATCH(SetPosition, SEQUENCE)
	MATCH(SetSliderValue, SEQUENCE)
	MATCH(SetSpeed, SEQUENCE)
	MATCH(SetTimer, SEQUENCE)
	MATCH(NewTimer, SEQUENCE)
	MATCH(SetTransparency, SEQUENCE)
	MATCH(SetVariable, SEQUENCE)
	MATCH(SetVolume, SEQUENCE)
	MATCH(Step, SEQUENCE)
	MATCH(StorePersistent, SEQUENCE)
	MATCH(Subtract, SEQUENCE)
	MATCH(TestVariable, SEQUENCE)
	MATCH(ToggleItem, SEQUENCE)
	MATCH(TransitionTo, SEQUENCE)
	MATCH(ConnectionTagOrNull, CHOICE)
	MATCH(ComparisonValue, CHOICE)
	MATCH(EmulatedEventData, CHOICE)
	MATCH(NewColour, CHOICE)
	MATCH(NewContent, CHOICE)
	MATCH(NewFont, CHOICE)
	MATCH(NewReferencedContent, SEQUENCE)
	MATCH(NewContentSize, CHOICE)
	MATCH(NewVariableValue, CHOICE)
	MATCH(Parameter, CHOICE)
	MATCH(Point, SEQUENCE)
	MATCH(Rational, SEQUENCE)
	MATCH(ObjectReference, CHOICE)
	MATCH(ExternalReference, SEQUENCE)
	MATCH(IndirectReference, CHOICE)
	MATCH(GenericObjectReference, CHOICE)
	MATCH(GenericContentReference, CHOICE)
	MATCH(GenericInteger, CHOICE)
	MATCH(GenericBoolean, CHOICE)
	MATCH(GenericOctetString, CHOICE)
	MATCH(Colour, CHOICE)
	MATCH(XYPosition, SEQUENCE)
	MATCH(SetInputReg, SEQUENCE)	// MATCH(SetInputRegister, SEQUENCE)
	MATCH(SetCellPosition, SEQUENCE)
	MATCH(SetBitmapDecodeOffset, SEQUENCE)
	MATCH(GetBitmapDecodeOffset, SEQUENCE)
	MATCH(SetBackgroundColour, SEQUENCE)
	MATCH(SetTextColour, SEQUENCE)
	MATCH(SetFontAttributes, SEQUENCE)
	MATCH(SetVideoDecodeOffset, SEQUENCE)
	MATCH(GetVideoDecodeOffset, SEQUENCE)
	MATCH(SetSliderParameters, SEQUENCE)
	MATCH(GetFocusPosition, SEQUENCE)
	MATCH(SetFocusPosition, SEQUENCE)
	MATCH(OctetString, CHOICE);
	MATCH(ActionSlotSeq, CHOICE);

	fprintf(stderr, "Unknown ASN1 type: %s\n", name);
	exit(EXIT_FAILURE);

	return ASN1TYPE_UNKNOWN;
}
